### ISSUE TITLE
As a user I want to deploy a Java application from GitHub into as a container into an OpenShift 4 cluster using GitHub Action so that my workflow is triggered by a new push on a branch

### ISSUE THREAD

**Issue by markito** [redhat-developer/openshift-actions#49]
Assumptions:
* Cluster has internet access

Potential Outcomes: 
* Knative action / Dev CLI pack

**Comment by divyansh42** [comment]
As discussed, I have split this issue into 3:

- [Buildah action to build an image](https://github.com/redhat-developer/openshift-actions/issues/56)
- [S2i action to build an image](https://github.com/redhat-developer/openshift-actions/issues/57)
- [Push action to push an image to registry](https://github.com/redhat-developer/openshift-actions/issues/58)

**Comment by tetchel** [comment]
closing because we replaced with divyanshu's issues
