### ISSUE TITLE
Explore the creation of a Login action

### ISSUE THREAD

**Issue by markito** [redhat-developer/openshift-actions#54]

**Comment by lstocchi** [comment]
The Login action should allows users to authenticate to an OpenShift cluster. The action should also provide authentication to additional k8s actions in the same workflow. 

@tetchel added a small description as it was empty. If i misunderstood something, change it as you like :smile:

**Comment by tetchel** [comment]
The initial login action is done. I would appreciate more validation through usage and any feedback on the documentation / flow but here it is. https://github.com/redhat-actions/oc-login
